
# ── STAGE 1: BUILD Angular ──────────────────────────
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json .
RUN npm install

COPY . .
RUN npm run build -- --configuration production

# ── STAGE 2: SERVE with Nginx ───────────────────────
FROM nginx:alpine AS final
COPY --from=build /app/dist/employee.ui/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80